name: multiling-twitter
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adjusttext=0.7.3.1
  - anyio=2.1.0
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.38.0
  - atk-1.0=2.36.0
  - attrs=20.3.0
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - bcrypt=3.2.0
  - beautifulsoup4=4.9.3
  - bleach=3.3.0
  - bokeh=2.2.3
  - boost=1.74.0
  - boost-cpp=1.74.0
  - brotlipy=0.7.0
  - bs4=4.9.3
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - cairomm=1.12.2
  - cairomm-1.0=1.12.2
  - certifi=2021.5.30
  - cffi=1.14.4
  - cfitsio=3.470
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.1
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.4.4
  - curl=7.71.1
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.3.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - descartes=1.1.0
  - distributed=2021.2.0
  - entrypoints=0.3
  - epoxy=1.5.5
  - esda=2.3.6
  - expat=2.2.10
  - fiona=1.8.18
  - fontconfig=2.13.1
  - freetype=2.10.4
  - freexl=1.0.5
  - fribidi=1.0.10
  - fsspec=0.8.5
  - gdal=3.1.4
  - gdk-pixbuf=2.42.2
  - geopandas=0.8.2
  - geos=3.9.0
  - geotiff=1.6.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.6
  - glib-tools=2.66.6
  - gmp=6.2.1
  - gobject-introspection=1.66.1
  - graphite2=1.3.13
  - gtk3=3.24.24
  - harfbuzz=2.7.4
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - hicolor-icon-theme=0.17
  - icu=68.1
  - idna=2.10
  - importlib-metadata=3.4.0
  - importlib_metadata=3.4.0
  - ipykernel=5.5.0
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - json-c=0.13.1
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter_client=6.1.11
  - jupyter_core=4.7.1
  - jupyter_server=1.3.0
  - jupyterlab=3.0.7
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.2.0
  - kealib=1.4.14
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdap4=3.20.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgdal=3.1.4
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.6
  - libgomp=9.3.0
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.7.4
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libpq=12.3
  - libpysal=4.4.0
  - librsvg=2.50.3
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxml2=2.9.10
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - msgpack-python=1.0.2
  - munch=2.5.0
  - nbclassic=0.2.6
  - nbclient=0.5.2
  - nbconvert=5.6.1
  - nbformat=5.1.2
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - notebook=6.2.0
  - numpy=1.20.1
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.11.4
  - pandocfilters=1.4.2
  - pango=1.42.4
  - paramiko=2.7.2
  - parso=0.8.1
  - partd=1.1.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0.1
  - pixman=0.40.0
  - plotly=4.14.3
  - poppler=0.89.0
  - poppler-data=0.4.10
  - postgresql=12.3
  - pot=0.7.0
  - proj=7.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.14
  - psutil=5.8.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pycairo=1.20.0
  - pycparser=2.20
  - pygments=2.7.4
  - pygobject=3.38.0
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python-dotenv=0.15.0
  - python-louvain=0.15
  - python_abi=3.7
  - pytz=2021.1
  - pyxlsb=1.0.8
  - pyyaml=5.4.1
  - pyzmq=22.0.1
  - readline=8.0
  - requests=2.25.1
  - retrying=1.3.3
  - rtree=0.9.7
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - sigcpp-2.0=2.10.3
  - six=1.15.0
  - sniffio=1.2.0
  - sortedcontainers=2.3.0
  - soupsieve=2.0.1
  - sparsehash=2.0.3
  - sqlite=3.34.0
  - tblib=1.6.0
  - terminado=0.9.2
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tiledb=2.2.3
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing_extensions=3.7.4.3
  - tzcode=2021a
  - tzdata=2021a
  - urllib3=1.26.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xerces-c=3.2.3
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstandard=0.15.1
  - zstd=1.4.8
  - pip:
    - aiohttp==3.7.3
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - async-timeout==3.0.1
    - blessings==1.7
    - cachetools==4.2.1
    - chardet==3.0.4
    - colorful==0.5.4
    - filelock==3.0.12
    - google-api-core==1.26.0
    - google-auth==1.26.1
    - googleapis-common-protos==1.52.0
    - gpustat==0.6.0
    - grpcio==1.35.0
    - hiredis==1.1.0
    - ipfn==1.4.1
    - multidict==5.1.0
    - nvidia-ml-py3==7.352.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - protobuf==3.14.0
    - py-spy==0.3.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycld2==0.41
    - redis==3.5.3
    - rsa==4.7
    - tqdm==4.56.2
    - yarl==1.6.3
